site_name: Documentation Site - Kuwait & Iraq vACC
site_url: https://docs.gulfvacc.net

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Mulish
  palette:
    - scheme: default
      primary: custom
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    - scheme: slate
      primary: custom
      accent: green
      toggle:
        icon: material/weather-night
        name: Light mode

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - content.tooltips

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/
    - icon: fontawesome/brands/discord
      link: https://community.vatsim.net
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - toc:
      permalink: true

plugins:
  - search
  - awesome-pages

copyright: ""